print(" Mera pehla github project")
name=input("Muazzma Khalid:")
print ("Salam",name)
num1=int(input("Pehla number: "))
num2=int(input("Dosra number:"))
print ("Add:",num1 + num2)
print("Subtract:",num1 - num2)
print("Multiply:",num1 * num2)
print ("Divide:",num1/ num2)
